### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by anazhibaj** [VIS-2129-F2020/anazhibaj-vis#3]
Hi! This is my third assignment! I hope you enjoy. 
Link:
https://vis-2129-f2020.github.io/anazhibaj-vis/200928_Assignment-3.html

**Comment by anazhibaj** [comment]
Hello again! 

I made some adjustments to my previous submission of Assignment 3. This is the final final final version. Thank you for the extension of the deadline, and I hope you enjoy! 
link: https://vis-2129-f2020.github.io/anazhibaj-vis/Assignment-3

**Comment by bauranov** [comment]
Great work! I have two very nitpicky comments:

- Maps with points are difficult to read, maybe it makes sense to make the points larger, especially in the section *Finding the closest point*.
- It's not exactly clear what *climate vulnerability* is, why should we map it, and what is its relationship with trees (it could be related to flooding, urban heat islands, CO2 emissions, etc). Whenever you're displaying a variable that is not self-explanatory, add some context to it. The visualizations would be more impactful if you explained some of the issues mentioned above.
