### ISSUE TITLE
Problem with knitting 

### ISSUE THREAD

**Issue by anazhibaj** [VIS-2129-F2020/anazhibaj-vis#4]
Hi Carole! Hi Aleks! As we discussed, I had trouble knitting Assignment 4. During your office hours, we removed some of the unnecessary lines of code. I committed the Rmd file to Git. 
Link: https://github.com/VIS-2129-F2020/anazhibaj-vis/blob/master/201002_Assignment%204.Rmd
https://vis-2129-f2020.github.io/anazhibaj-vis/201002_Assignment-4.html

I hope it runs! Thank you for taking the time to troubleshoot the code with me; looking forward to your feedback.

**Comment by c-voulgaris** [comment]
I can get it to knit either - for this one assignment, Aleks will just download your Rmd file and run it without knitting, so he can grade it that way. If you haven't already, go ahead and submit this assignment for grading as-is.
