### ISSUE TITLE
Assignment 4 ready to be graded

### ISSUE THREAD

**Issue by anazhibaj** [VIS-2129-F2020/anazhibaj-vis#5]
Hi Carole! Hi Aleks! This is my submission for assignment 4. I had a problem knitting the file, created an issue with the problem, and the professor tried to knit the file but couldn't. 

This is the link I knitted to far: https://vis-2129-f2020.github.io/anazhibaj-vis/201002_Assignment-4.html
Rmd: https://github.com/VIS-2129-F2020/anazhibaj-vis/blob/master/201002_Assignment%204.Rmd

Thank you!

**Comment by bauranov** [comment]
Great topic for the isochrone analysis. This smells like a research paper :) 
Make sure the html is free of unnecessary clutter (warnings and stuff). Keep up the good work!
