### ISSUE TITLE
Assignment 6

### ISSUE THREAD

**Issue by anazhibaj** [VIS-2129-F2020/anazhibaj-vis#6]
Hi! Assignment 6 is ready to be graded. I hope you enjoy!

Map:
https://vis-2129-f2020.github.io/anazhibaj-vis/parkslowincome.html

https://vis-2129-f2020.github.io/anazhibaj-vis/201026_Assignment6_2.html

**Comment by c-voulgaris** [comment]
Thanks! Please submit the html file via Canvas.
